# Bitcoin IP banlist dataset
# This file contains a list of entities and their IP addresses that could be
# malicious actors on the Bitcoin network.

[[entities]]
name = "LinkingLion"
added = 2023-03-27
tags = []
description = """
This entity connects from four IP address ranges to listening Bitcoin nodes
using fake user agents. While many of the connections are short-lived, some
listen for transaction announcements. This might allow the entity to link
transactions to IP addresses.

The IP address ranges are annouced by Lionlink Networks (AS54098):

- `162.218.65.0/24`
- `209.222.252.0/24`
- `91.198.115.0/24`
- `2604:d500:4:1::/64`

Some of these IP ranges have been making connections to Bitcoin nodes since
at least 2018 and connect to nodes on the Monero network too. It's unclear if
they are VPN endpoints. The entity could be a blockchain analysis company
enhancing their products with the collected data.

More details: https://b10c.me/observations/06-linkinglion
"""
ips = [
  "162.218.65.0/24",
  "209.222.252.0/24",
  "91.198.115.0/24",
  "2604:d500:4:1::/64",
]

# INV-eaters below.
# These entites open long-lived connetions to us and receive a lot of INVs
# from us, while never sending a getdata or an INV themself. Some of these are
# "spy-nodes", others are "network monitoring tools" by researchers.

[[entities]]
name = "KIT DSN Bitcoin Monitoring"
added = 2023-05-15
tags = []
description = """
The DSN group from Karlsruhe Insitute of Technology run a Bitcoin network
monitoring tool that connects to all reachable nodes on the network. This
tool does not relay or request transactions.

The entity uses the user agent: `/dsn.tm.kit.edu/bitcoin:0.9.99/`.

More details: https://www.dsn.kastel.kit.edu/bitcoin/
"""
ips = [
  "129.13.189.200",
  "129.13.189.202",
  "141.20.33.66",
  "2a00:1398:4:2a03:4e52:62ff:fe22:6c13",
  "2a00:1398:4:2a03:921b:eff:fe35:aed9",
]

[[entities]]
name = "nodes.mom.market"
added = 2023-05-15
tags = []
description = """

A mom.market also hosts a tool called "BitFence" described by them as
"Global Bitcoin Node and Gateway Live Monitoring & Cyber-defence". It listens
to INVs but does not request or relay transactions.

The entity uses the user agent: `/nodes.mom.market:0.2/`.

More details: https://nodes.mom.market/

"""
ips = [
  "94.237.44.67",
  "2a04:3544:1000:1510:b08f:6fff:fe1b:3007",
]

[[entities]]
name = "Yuroval"
added = 2023-05-15
tags = []
description = """
A Bitcoin client hosted with fvds.ru that listens to INVs but never requests
transactions.
"""
ips = [
  "2a01:230:4:87b::2",
  "212.109.218.99",
]

[[entities]]
name = "bitnodes.io"
added = 2023-05-15
tags = []
description = """
The website bitnodes.io shows Bitcoin network node counts and statistics. The
client listens to INVs but never requests or relays transactions. The entity
uses the user agent: `/bitnodes.io:0.3/`.

The IP address `95.165.29.10` uses the same user agent but is not listed on the
bitnodes.io website.
"""
ips = [
  "88.198.10.156",
  "88.198.10.155",
  "2a01:4f8:222:291f::2",
  "95.165.29.10",
]

[[entities]]
name = "bitnodes.earn.com"
added = 2023-05-15
tags = []
description = """
This entity identifies as bitnodes.earn.com, though earn.com does not exist
anymore. This might be someone using the user agent to listen to INVs. They
don't request or relay transactions.

The entity uses the user agent: `/bitnodes.earn.com:0.1/`.
"""
ips = [
  "2a03:b0c0:2:d0::4bc:2001",
  "188.166.69.73",
]

[[entities]]
name = "Brno University of Technology / netsearch.cz COINØMON"
added = 2023-05-15
tags = []
description = """
The Brno University of Technology runs Bitcoin clients that open connections
and idenitify as `/bitcoinj:0.16.2/Bitcoin Wallet:9.26/` on multiple IP
addresses. These clients do not request or relay transactions. These clients
might be related to netsearch.cz's COINØMON.

More information:
- https://www.issworldtraining.com/ISS_WEBINARS/2022SeptBrno.htm
- https://www.netsearch.cz/products/coinomon/
"""
ips = [
  "2001:67c:1220:808:d5:a28:cc2:27c5",
  "2001:67c:1220:808:f6:d81b:74a:ae60",
  "147.229.8.240",
]

[[entities]]
name = "Miscellaneous Digital Ocean nodes"
added = 2023-05-15
tags = []
description = """
Digital Ocean 

"""
ips = [
  "46.101.233.24",
  "2a03:b0c0:3:d0::1458:f001",
  "167.172.96.96",
  "64.227.74.130",
]

[[entities]]
name = "bitcoinstats.com"
added = 2023-05-15
tags = []
description = """
The enity does not request or relay transactions but listens to INVs.

The entity uses the user agent: `/btcwire:0.5.0/bitcoinstats.com:0.2/`.
"""
ips = [
  "34.72.221.216",
]

[[entities]]
name = "Miscellaneous Google Cloud nodes"
added = 2023-05-15
tags = []
description = """
The enity does not request or relay transactions but listens to INVs.
"""
ips = [
  "34.28.102.226",
]

[[entities]]
name = "Zen Internet Ltd DSL IP"
added = 2023-05-15
tags = []
description = """
The enity does not request or relay transactions but listens to INVs.
"""
ips = [
  "88.97.103.200",
]
